# Generated by Django 2.1.5 on 2019-01-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
            ],
        ),
    ]
