# Generated by Django 2.1.5 on 2019-01-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_prob_update', models.IntegerField(default=1548953248.134915)),
                ('last_top1_update', models.IntegerField(default=1548953248.134915)),
                ('last_top2_update', models.IntegerField(default=1548953248.134915)),
                ('last_top3_update', models.IntegerField(default=1548953248.134915)),
                ('last_all_top_update', models.IntegerField(default=1548953248.134915)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='lastupdate',
            field=models.IntegerField(default=1548953248.1339188),
        ),
        migrations.AddField(
            model_name='member',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='target',
            field=models.IntegerField(default=1),
        ),
    ]
