# Generated by Django 2.1.5 on 2019-02-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190131_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateManager',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastupdate',
        ),
    ]
